### PR TITLE
added becnhmark workflow on PR

### PR DESCRIPTION
**Pull request by bhautikpip**
1. Added benchmark workflow which runs on every PR (idea is to get performance numbers on every released version upstream)

### CODE REVIEW

**Comment by anuraaga** [comment]
I don't think we have any code to benchmark - shouldn't these go upstream?

**Comment by bhautikpip** [comment]
> I don't think we have any code to benchmark - shouldn't these go upstream?

Yes I agree but the current benchmark code we have in this repository is only benchmarking aws specific components. We can definitely have the benchmark upstream but that would require a wide variety of benchmarks as per my understanding (needs more work). This PR is just an enhancement to what we have. Hence I thought of running the benchmark as workflow so at least we get an idea of the performance of released version and if next version needs improvement or not.

**Comment by anuraaga** [comment]
We should try to add these benchmarks upstream - any benchmark is better than no benchmark, they shouldn't resist that just because it doesn't benchmark every type of component. If there's a problem there, we can consider adding the benchmarks here but I wouldn't expect any issues.

**Comment by bhautikpip** [comment]
> We should try to add these benchmarks upstream - any benchmark is better than no benchmark, they shouldn't resist that just because it doesn't benchmark every type of component. If there's a problem there, we can consider adding the benchmarks here but I wouldn't expect any issues.

Do you think we should merge this PR or just close this? This PR is just a workflow for already existing benchmarks in this repository. Until we move all the benchmarks exist in this repository to upstream I think merging this PR wouldn't hurt or I am also fine with closing this out.

**Comment by anuraaga** [comment]
That's a good point, let's add this workflow but not forget to move the benchmarks upstream.

**Review by anuraaga — APPROVED** [review]

**Comment by bhautikpip** [comment]
Created issue for tracking this(moving benchmark to upstream) item: https://github.com/aws-observability/aws-otel-go/issues/24

**Pull request merged**
